/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/wVX74nmMGHS
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { AllergyLevel } from "@/shared/types/FiveStrands";

type Props = {
  name: string;
  level: AllergyLevel;
};

const levelColors: Record<AllergyLevel, string> = {
  1: "bg-green-500",
  2: "bg-orange-500",
  3: "bg-red-500",
};

export function AllergyCard({ name, level }: Props) {
  return (
    <Card className="w-full max-w-sm p-6 bg-card text-card-foreground">
      <div className="flex items-center gap-4">
        <div className="flex-1">
          <div className="text-muted-foreground">{name}</div>
        </div>
        <div className="flex flex-col items-end gap-1">
          <Badge className={`${levelColors[level]} text-primary-foreground`}>
            Level {level}
          </Badge>
        </div>
      </div>
    </Card>
  );
}
